// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
   schema: 'prisma/schema',
   migrations: {
      path: 'prisma/migrations',
      // `npm run db:seed` (prisma db seed) runs this: a local demo workspace, see prisma/seed.ts
      seed: 'tsx prisma/seed.ts'
   },
   datasource: {
      url: process.env['DATABASE_URL']
   }
});
