import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
   // shadcn's theme in globals.css reads the main font from --font-sans
   variable: '--font-sans',
   subsets: ['latin']
});

const geistMono = Geist_Mono({
   variable: '--font-geist-mono',
   subsets: ['latin']
});

export const metadata: Metadata = {
   title: 'SaaS App',
   description: 'Generated by create next app'
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
   return (
      <html lang='en' className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
         {/* Browser extensions (e.g. ColorZilla) add attributes to <body> before React loads.
             This ignores attribute mismatches on <body> itself; its children are still checked. */}
         <body className='min-h-full flex flex-col' suppressHydrationWarning>
            {children}
         </body>
      </html>
   );
}
